default_install_hook_types:
  - pre-commit
  - commit-msg
  - post-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [ --markdown-linebreak-ext=md ]
    - id: check-toml
    - id: detect-private-key

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.19
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-format
        always_run: true
      - id: ruff-check
        args: [ --output-format, concise, --exit-zero ]

  # local hooks
  - repo: .
    rev: main
    hooks:
      - id: check-commit-msg
        # name: check-commit-msg
        # entry: cz
        # args: [ -n,  cz_troi_hook, check, --allow-abort, --commit-msg-file]
        # language: python
        # language_version: python3
        # minimum_pre_commit_version: "1.4.3"
        # stages: [commit-msg]

      - id: changelog-helper
        # name: changelog-helper
        # entry: bash -c "touch .commit"
        # language: system
        # always_run: true
        # stages: [commit-msg]

      - id: recreate-changelog
        # name: recreate-changelog
        # entry: scripts/recreate_changelog.sh
        # language: script
        # always_run: true
        # stages: [post-commit]
